import sqlite3 from 'sqlite3';
import { open } from 'sqlite';

async function initializeDatabase() {
  // Открываем или создаем базу данных
  const db = await open({
    filename: 'products.db',
    driver: sqlite3.Database,
  });

  // Создаем таблицу products
  await db.exec(`
    CREATE TABLE IF NOT EXISTS products (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      category TEXT,
      brand TEXT,
      model TEXT,
      name TEXT,
      price INTEGER
    );
  `);

  console.log('Таблица products создана.');

  // Данные для вставки
  const productsData = [
    // Часы
    {
      category: 'Часы',
      brand: 'Apple',
      model: 'Apple Watch Ultra 2',
      name: 'Ultra 2(2024) 49 Black OB Black',
      price: 85000,
    },
    {
      category: 'Часы',
      brand: 'Apple',
      model: 'Apple Watch Series 10',
      name: 'S10 42mm Black/Black',
      price: 43000,
    },
    {
      category: 'Часы',
      brand: 'Apple',
      model: 'Apple Watch Series 10',
      name: 'S10 46mm Black/Black',
      price: 45000,
    },
    {
      category: 'Часы',
      brand: 'Apple',
      model: 'Apple Watch SE 2023',
      name: 'SE 2023 40mm Starlight',
      price: 22500,
    },
    {
      category: 'Часы',
      brand: 'Apple',
      model: 'Apple Watch SE 2023',
      name: 'SE 2023 40mm Midnight',
      price: 21500,
    },
    {
      category: 'Часы',
      brand: 'Apple',
      model: 'Apple Watch SE 2024',
      name: 'SE 2024 40mm Silver',
      price: 22500,
    },
    {
      category: 'Часы',
      brand: 'Apple',
      model: 'Apple Watch SE 2024',
      name: 'SE 2024 40mm Midnight',
      price: 22000,
    },
    {
      category: 'Часы',
      brand: 'Apple',
      model: 'Apple Watch SE 2024',
      name: 'SE 2024 44mm Midnight',
      price: 23500,
    },
  
    // Samsung Часы
    {
      category: 'Часы',
      brand: 'Samsung',
      model: 'Galaxy Watch',
      name: '5 40mm Pink Gold',
      price: 14000,
    },
    {
      category: 'Часы',
      brand: 'Samsung',
      model: 'Galaxy Watch',
      name: '5 44mm Sapphire',
      price: 16500,
    },
    {
      category: 'Часы',
      brand: 'Samsung',
      model: 'Galaxy Watch',
      name: '5 44mm Silver',
      price: 16500,
    },
    {
      category: 'Часы',
      brand: 'Samsung',
      model: 'Galaxy Watch',
      name: '5 Pro 45mm Gray',
      price: 19000,
    },
    {
      category: 'Часы',
      brand: 'Samsung',
      model: 'Galaxy Watch',
      name: '7 40mm Green',
      price: 21000,
    },
    {
      category: 'Часы',
      brand: 'Samsung',
      model: 'Galaxy Watch',
      name: '7 40mm Cream',
      price: 21000,
    },
    {
      category: 'Часы',
      brand: 'Samsung',
      model: 'Galaxy Watch',
      name: '7 44mm Silver',
      price: 23000,
    },
    {
      category: 'Часы',
      brand: 'Samsung',
      model: 'Galaxy Watch',
      name: 'Watch Ultra 47mm White/White',
      price: 44500,
    },
    {
      category: 'Часы',
      brand: 'Samsung',
      model: 'Galaxy Watch',
      name: 'Watch Ultra 47mm Gray/Orange',
      price: 45000,
    },
  
    // Garmin Часы
    {
      category: 'Часы',
      brand: 'Garmin',
      model: 'Garmin Vivomove 3',
      name: 'Garmin Vivomove 3 Silver',
      price: 18500,
    },
    {
      category: 'Часы',
      brand: 'Garmin',
      model: 'Garmin Vivomove 3s',
      name: 'Garmin Vivomove 3s Blue',
      price: 16600,
    },
    {
      category: 'Часы',
      brand: 'Garmin',
      model: 'Garmin Epix Pro',
      name: 'Garmin Epix Pro 47mm Black',
      price: 80000,
    },
  
    // OnePlus Часы
    {
      category: 'Часы',
      brand: 'OnePlus',
      model: 'OnePlus Watch',
      name: 'OnePlus Watch 2 Black',
      price: 19500,
    },
    {
      category: 'Часы',
      brand: 'OnePlus',
      model: 'OnePlus Watch',
      name: 'OnePlus Watch 2R Gray',
      price: 16500,
    },
  
    // Смартфоны Apple
    {
      category: 'Смартфоны',
      brand: 'Apple',
      model: 'iPhone 16 Pro Max',
      name: '16 Pro Max 256 Black Titanium 🇯🇵',
      price: 127500,
    },
    {
      category: 'Смартфоны',
      brand: 'Apple',
      model: 'iPhone 16 Pro Max',
      name: '16 Pro Max 256 Natural Titanium 🇯🇵',
      price: 128500,
    },
    {
      category: 'Смартфоны',
      brand: 'Apple',
      model: 'iPhone 16 Pro Max',
      name: '16 Pro Max 256 White Titanium 🇯🇵',
      price: 128500,
    },
    {
      category: 'Смартфоны',
      brand: 'Apple',
      model: 'iPhone 16 Pro Max',
      name: '16 Pro Max 1Tb Natural Titanium 🇯🇵',
      price: 170000,
    },
    {
      category: 'Смартфоны',
      brand: 'Apple',
      model: 'iPhone 16 Pro Max',
      name: '16 Pro Max 1Tb Desert Titanium 🇯🇵',
      price: 170000,
    },
    {
      category: 'Смартфоны',
      brand: 'Apple',
      model: 'iPhone 16 Pro',
      name: '16 Pro 128 Natural Titanium 🇯🇵',
      price: 107500,
    },
    {
      category: 'Смартфоны',
      brand: 'Apple',
      model: 'iPhone 16 Pro',
      name: '16 Pro 128 Black Titanium 🇯🇵',
      price: 108500,
    },
    {
      category: 'Смартфоны',
      brand: 'Apple',
      model: 'iPhone 16 Pro',
      name: '16 Pro 128 White Titanium 🇯🇵',
      price: 107500,
    },
    {
      category: 'Смартфоны',
      brand: 'Apple',
      model: 'iPhone 16 Pro',
      name: '16 Pro 128 Desert Titanium 🇯🇵',
      price: 108000,
    },
    {
      category: 'Смартфоны',
      brand: 'Apple',
      model: 'iPhone 16 Pro',
      name: '16 Pro 512 Desert Titanium 🇯🇵',
      price: 138000,
    },
    {
      category: 'Смартфоны',
      brand: 'Apple',
      model: 'iPhone 16 Pro',
      name: '16 Pro 512 Natural Titanium 🇯🇵',
      price: 138000,
    },
    {
      category: 'Смартфоны',
      brand: 'Apple',
      model: 'iPhone 16 Plus',
      name: '16 Plus 128 Black 🇯🇵',
      price: 95000,
    },
    {
      category: 'Смартфоны',
      brand: 'Apple',
      model: 'iPhone 16 Plus',
      name: '16 Plus 128 Teal 🇯🇵',
      price: 95000,
    },
    {
      category: 'Смартфоны',
      brand: 'Apple',
      model: 'iPhone 16 Plus',
      name: '16 Plus 128 Ultramarine 🇯🇵',
      price: 95000,
    },
    {
      category: 'Смартфоны',
      brand: 'Apple',
      model: 'iPhone 16',
      name: '16 128 Black 🇮🇳',
      price: 82000,
    },
    {
      category: 'Смартфоны',
      brand: 'Apple',
      model: 'iPhone 16',
      name: '16 128 Pink 🇮🇳',
      price: 82000,
    },
    {
      category: 'Смартфоны',
      brand: 'Apple',
      model: 'iPhone 16',
      name: '16 256 White 🇯🇵',
      price: 96000,
    },
    {
      category: 'Смартфоны',
      brand: 'Apple',
      model: 'iPhone 15 Pro Max',
      name: '15 Pro Max 256 Black Titanium 🇯🇵',
      price: 117000,
    },
    {
      category: 'Смартфоны',
      brand: 'Apple',
      model: 'iPhone 15 Plus',
      name: '15 Plus 128 Blue 🇮🇳',
      price: 85000,
    },
    {
      category: 'Смартфоны',
      brand: 'Apple',
      model: 'iPhone 15 Plus',
      name: '15 Plus 128 Green 🇮🇳',
      price: 85000,
    },
    {
      category: 'Смартфоны',
      brand: 'Apple',
      model: 'iPhone 15 Plus',
      name: '15 Plus 128 Pink 🇮🇳',
      price: 85000,
    },
    {
      category: 'Смартфоны',
      brand: 'Apple',
      model: 'iPhone 15',
      name: '15 128 Green 🇮🇳',
      price: 69000,
    },
    {
      category: 'Смартфоны',
      brand: 'Apple',
      model: 'iPhone 15',
      name: '15 256 Pink 🇮🇳',
      price: 87000,
    },
    {
      category: 'Смартфоны',
      brand: 'Apple',
      model: 'iPhone 14 Pro Max',
      name: '14 Pro Max 1Tb Gold 🇯🇵',
      price: 131000,
    },
    {
      category: 'Смартфоны',
      brand: 'Apple',
      model: 'iPhone 14',
      name: '14 128 Starlight 🇨🇳',
      price: 64500,
    },
    {
      category: 'Смартфоны',
      brand: 'Apple',
      model: 'iPhone 14',
      name: '14 128 Purple 🇮🇳',
      price: 64000,
    },
    {
      category: 'Смартфоны',
      brand: 'Apple',
      model: 'iPhone 13',
      name: '13 128 Green 🇮🇳',
      price: 51000,
    },
    {
      category: 'Смартфоны',
      brand: 'Apple',
      model: 'iPhone 13',
      name: '13 128 Blue 🇮🇳',
      price: 51000,
    },
    {
      category: 'Смартфоны',
      brand: 'Apple',
      model: 'iPhone 13',
      name: '13 256 Pink 🇮🇳',
      price: 67000,
    },
    {
      category: 'Смартфоны',
      brand: 'Apple',
      model: 'iPhone 13',
      name: '13 256 Green 🇮🇳',
      price: 66000,
    },
    {
      category: 'Смартфоны',
      brand: 'Apple',
      model: 'iPhone 12',
      name: '12 128 Black 🇮🇳',
      price: 46500,
    },
    {
      category: 'Смартфоны',
      brand: 'Apple',
      model: 'iPhone 12',
      name: '12 128 Purple 🇮🇳',
      price: 46500,
    },
    {
      category: 'Смартфоны',
      brand: 'Apple',
      model: 'iPhone 12',
      name: '12 64 Blue 🇮🇳',
      price: 44000,
    },
    {
      category: 'Смартфоны',
      brand: 'Apple',
      model: 'iPhone 12',
      name: '12 64 White 🇮🇳',
      price: 44000,
    },
    {
      category: 'Смартфоны',
      brand: 'Apple',
      model: 'iPhone 11',
      name: '11 64 White 🇨🇱',
      price: 38000,
    },
  
    // Samsung Смартфоны
    {
      category: 'Смартфоны',
      brand: 'Samsung',
      model: 'Samsung A05',
      name: 'A05 4/128 Черный',
      price: 10100,
    },
    {
      category: 'Смартфоны',
      brand: 'Samsung',
      model: 'Samsung A05',
      name: 'A05 6/128 Черный',
      price: 11900,
    },
    {
      category: 'Смартфоны',
      brand: 'Samsung',
      model: 'Samsung A05S',
      name: 'A05s 4/64 Черный',
      price: 10300,
    },
    {
      category: 'Смартфоны',
      brand: 'Samsung',
      model: 'Samsung A05S',
      name: 'A05s 4/64 Фиолетовый',
      price: 10300,
    },
    {
      category: 'Смартфоны',
      brand: 'Samsung',
      model: 'Samsung A05S',
      name: 'A05s 6/128 Фиолетовый',
      price: 12300,
    },
    {
      category: 'Смартфоны',
      brand: 'Samsung',
      model: 'Samsung A05S',
      name: 'A05s 6/128 Серебро',
      price: 12300,
    },
    {
      category: 'Смартфоны',
      brand: 'Samsung',
      model: 'Samsung A06',
      name: 'A06 4/64 Черный',
      price: 9200,
    },
    {
      category: 'Смартфоны',
      brand: 'Samsung',
      model: 'Samsung A06',
      name: 'A06 4/64 Светло-Синий',
      price: 9200,
    },
    {
      category: 'Смартфоны',
      brand: 'Samsung',
      model: 'Samsung A06',
      name: 'A06 6/128 Золотой',
      price: 11500,
    },
    {
      category: 'Смартфоны',
      brand: 'Samsung',
      model: 'Samsung A06',
      name: 'A06 6/128 Черный',
      price: 11500,
    },
    {
      category: 'Смартфоны',
      brand: 'Samsung',
      model: 'Samsung A06',
      name: 'A06 6/128 Светло-Синий',
      price: 11500,
    },
    {
      category: 'Смартфоны',
      brand: 'Samsung',
      model: 'Samsung A14',
      name: 'A14 4/128 Черный',
      price: 12300,
    },
    {
      category: 'Смартфоны',
      brand: 'Samsung',
      model: 'Samsung A15',
      name: 'A15 4/128 Черно-Синий',
      price: 14500,
    },
    {
      category: 'Смартфоны',
      brand: 'Samsung',
      model: 'Samsung A15',
      name: 'A15 4/128 Желтый',
      price: 14500,
    },
    {
      category: 'Смартфоны',
      brand: 'Samsung',
      model: 'Samsung A15',
      name: 'A15 4/128 Синий',
      price: 14500,
    },
    {
      category: 'Смартфоны',
      brand: 'Samsung',
      model: 'Samsung A16',
      name: 'A16 4/128 Серый',
      price: 15300,
    },
    {
      category: 'Смартфоны',
      brand: 'Samsung',
      model: 'Samsung A16',
      name: 'A16 4/128 Зеленый',
      price: 15300,
    },
    {
      category: 'Смартфоны',
      brand: 'Samsung',
      model: 'Samsung A16',
      name: 'A16 4/128 Черный',
      price: 15300,
    },
    {
      category: 'Смартфоны',
      brand: 'Samsung',
      model: 'Samsung A16',
      name: 'A16 6/128 Серый',
      price: 16700,
    },
    {
      category: 'Смартфоны',
      brand: 'Samsung',
      model: 'Samsung A16',
      name: 'A16 8/256 5G Золотой',
      price: 22000,
    },
    {
      category: 'Смартфоны',
      brand: 'Samsung',
      model: 'Samsung A16',
      name: 'A16 8/256 5G Светло-Зеленый',
      price: 22000,
    },
    {
      category: 'Смартфоны',
      brand: 'Samsung',
      model: 'Samsung A23',
      name: 'A23 4/64 Персиковый',
      price: 11300,
    },
    {
      category: 'Смартфоны',
      brand: 'Samsung',
      model: 'Samsung A25',
      name: 'A25 8/256 Лайм',
      price: 21800,
    },
    {
      category: 'Смартфоны',
      brand: 'Samsung',
      model: 'Samsung A25',
      name: 'A25 8/256 Светло-Синий',
      price: 21800,
    },
    {
      category: 'Смартфоны',
      brand: 'Samsung',
      model: 'Samsung A25',
      name: 'A25 8/256 Синий',
      price: 21800,
    },
    {
      category: 'Смартфоны',
      brand: 'Samsung',
      model: 'Samsung A35',
      name: 'A35 8/128 Голубой',
      price: 24400,
    },
    {
      category: 'Смартфоны',
      brand: 'Samsung',
      model: 'Samsung A35',
      name: 'A35 8/128 Лиловый',
      price: 24400,
    },
    {
      category: 'Смартфоны',
      brand: 'Samsung',
      model: 'Samsung A35',
      name: 'A35 8/256 Нави',
      price: 27300,
    },
    {
      category: 'Смартфоны',
      brand: 'Samsung',
      model: 'Samsung A54',
      name: 'A54 8/256 Гб Белый',
      price: 30000,
    },
    {
      category: 'Смартфоны',
      brand: 'Samsung',
      model: 'Samsung A54',
      name: 'A54 8/256 Гб Графит',
      price: 30000,
    },
    {
      category: 'Смартфоны',
      brand: 'Samsung',
      model: 'Samsung A55',
      name: 'A55 8/128 Гб Нави',
      price: 30000,
    },
    {
      category: 'Смартфоны',
      brand: 'Samsung',
      model: 'Samsung A55',
      name: 'A55 8/128 Гб Лаванда',
      price: 30300,
    },
    {
      category: 'Смартфоны',
      brand: 'Samsung',
      model: 'Samsung A55',
      name: 'A55 12/256 Гб Лаванда',
      price: 35500,
    },
    {
      category: 'Смартфоны',
      brand: 'Samsung',
      model: 'Samsung A55',
      name: 'A55 12/256 Гб Голубой',
      price: 35500,
    },
    {
      category: 'Смартфоны',
      brand: 'Samsung',
      model: 'Samsung М54',
      name: 'М54 8/256 Синий',
      price: 29000,
    },
    {
      category: 'Смартфоны',
      brand: 'Samsung',
      model: 'Samsung М54',
      name: 'М54 8/256 Серебро',
      price: 29000,
    },
    {
      category: 'Смартфоны',
      brand: 'Samsung',
      model: 'Samsung М55',
      name: 'М55 8/256 Черный',
      price: 31500,
    },
    {
      category: 'Смартфоны',
      brand: 'Samsung',
      model: 'Samsung М55',
      name: 'М55 8/256 Зеленый',
      price: 31500,
    },
    {
      category: 'Смартфоны',
      brand: 'Samsung',
      model: 'Samsung Note 20/Note 20 Ultra',
      name: 'Note 20 8/256 Бронзовый',
      price: 36800,
    },
    {
      category: 'Смартфоны',
      brand: 'Samsung',
      model: 'Samsung S21 FE',
      name: 'S21 FE 8/128 Зеленый',
      price: 30500,
    },
    {
      category: 'Смартфоны',
      brand: 'Samsung',
      model: 'Samsung S21 FE',
      name: 'S21 FE 8/128 Белый',
      price: 30500,
    },
    {
      category: 'Смартфоны',
      brand: 'Samsung',
      model: 'Samsung S21 FE',
      name: 'S21 FE 8/256 Нави',
      price: 36000,
    },
    {
      category: 'Смартфоны',
      brand: 'Samsung',
      model: 'Samsung S22',
      name: 'S22 8/128 Фиолетовый',
      price: 43000,
    },
    {
      category: 'Смартфоны',
      brand: 'Samsung',
      model: 'Samsung S22',
      name: 'S22 8/256 Фиолетовый',
      price: 47000,
    },
    {
      category: 'Смартфоны',
      brand: 'Samsung',
      model: 'Samsung S22',
      name: 'S22 8/256 Розовый',
      price: 47000,
    },
    {
      category: 'Смартфоны',
      brand: 'Samsung',
      model: 'Samsung S22 Plus',
      name: 'S22 Plus 8/128 Черный',
      price: 51000,
    },
    {
      category: 'Смартфоны',
      brand: 'Samsung',
      model: 'Samsung S22 Plus',
      name: 'S22 Plus 8/128 Зеленый',
      price: 51000,
    },
    {
      category: 'Смартфоны',
      brand: 'Samsung',
      model: 'Samsung S22 Plus',
      name: 'S22 Plus 8/256 Розовый',
      price: 54000,
    },
    {
      category: 'Смартфоны',
      brand: 'Samsung',
      model: 'Samsung S23',
      name: 'S23 8/128 Гб Зеленый',
      price: 49000,
    },
    {
      category: 'Смартфоны',
      brand: 'Samsung',
      model: 'Samsung S23',
      name: 'S23 8/128 Гб Черный',
      price: 49500,
    },
    {
      category: 'Смартфоны',
      brand: 'Samsung',
      model: 'Samsung S23',
      name: 'S23 8/256 Гб Черный',
      price: 53500,
    },
    {
      category: 'Смартфоны',
      brand: 'Samsung',
      model: 'Samsung S23FE',
      name: 'S23 FE 8/128 Мятный',
      price: 40000,
    },
    {
      category: 'Смартфоны',
      brand: 'Samsung',
      model: 'Samsung S23FE',
      name: 'S23 FE 8/256 Фиолетовый',
      price: 43000,
    },
    {
      category: 'Смартфоны',
      brand: 'Samsung',
      model: 'Samsung S23FE',
      name: 'S23 FE 8/256 Графитовый',
      price: 43000,
    },
    {
      category: 'Смартфоны',
      brand: 'Samsung',
      model: 'Samsung S23 Plus',
      name: 'S23 Plus 8/256 Гб Кремовый',
      price: 66000,
    },
    {
      category: 'Смартфоны',
      brand: 'Samsung',
      model: 'Samsung S23 Ultra',
      name: 'S23 Ultra 12/256 Гб Синий',
      price: 74000,
    },
    {
      category: 'Смартфоны',
      brand: 'Samsung',
      model: 'Samsung S23 Ultra',
      name: 'S23 Ultra 12/256 Гб Кремовый',
      price: 74000,
    },
    {
      category: 'Смартфоны',
      brand: 'Samsung',
      model: 'Samsung S23 Ultra',
      name: 'S23 Ultra 12/512 Гб Лаванда',
      price: 85000,
    },
    {
      category: 'Смартфоны',
      brand: 'Samsung',
      model: 'Samsung S23 Ultra',
      name: 'S23 Ultra 12/512 Гб Зеленый',
      price: 85000,
    },
    {
      category: 'Смартфоны',
      brand: 'Samsung',
      model: 'Samsung S24',
      name: 'S24 8/128 Гб Желтый',
      price: 57000,
    },
    {
      category: 'Смартфоны',
      brand: 'Samsung',
      model: 'Samsung S24',
      name: 'S24 8/128 Гб Лаванда',
      price: 58500,
    },
        {
      category: 'Смартфоны',
      brand: 'Samsung',
      model: 'Samsung S24',
      name: 'S24 8/256 Гб Желтый',
      price: 65500,
    },
    {
      category: 'Смартфоны',
      brand: 'Samsung',
      model: 'Samsung S24',
      name: 'S24 8/256 Гб Лаванда',
      price: 64500,
    },
    {
      category: 'Смартфоны',
      brand: 'Samsung',
      model: 'Samsung S24 FE',
      name: 'S24 FE 8/256 Гб Зеленый',
      price: 54000,
    },
    {
      category: 'Смартфоны',
      brand: 'Samsung',
      model: 'Samsung S24 FE',
      name: 'S24 FE 8/256 Гб Серый',
      price: 54000,
    },
    {
      category: 'Смартфоны',
      brand: 'Samsung',
      model: 'Samsung S24 FE',
      name: 'S24 FE 8/256 Гб Графит',
      price: 54000,
    },
    {
      category: 'Смартфоны',
      brand: 'Samsung',
      model: 'Samsung S24 FE',
      name: 'S24 FE 8/256 Гб Синий',
      price: 54000,
    },
    {
      category: 'Смартфоны',
      brand: 'Samsung',
      model: 'Samsung S24 FE',
      name: 'S24 FE 8/512 Гб Синий',
      price: 61000,
    },
    {
      category: 'Смартфоны',
      brand: 'Samsung',
      model: 'Samsung S24 FE',
      name: 'S24 FE 8/512 Гб Зеленый',
      price: 61000,
    },
    {
      category: 'Смартфоны',
      brand: 'Samsung',
      model: 'Samsung S24 Plus',
      name: 'S24 Plus 12/256 Гб Желтый',
      price: 72000,
    },
    {
      category: 'Смартфоны',
      brand: 'Samsung',
      model: 'Samsung S24 Plus',
      name: 'S24 Plus 12/256 Гб Черный',
      price: 72000,
    },
    {
      category: 'Смартфоны',
      brand: 'Samsung',
      model: 'Samsung S24 Plus',
      name: 'S24 Plus 12/512 Гб Желтый',
      price: 81000,
    },
    {
      category: 'Смартфоны',
      brand: 'Samsung',
      model: 'Samsung S24 Plus',
      name: 'S24 Plus 12/512 Гб Лаванда',
      price: 81000,
    },
    {
      category: 'Смартфоны',
      brand: 'Samsung',
      model: 'Samsung S24 Ultra',
      name: 'S24 Ultra 12/256 Гб Черный',
      price: 91500,
    },
    {
      category: 'Смартфоны',
      brand: 'Samsung',
      model: 'Samsung S24 Ultra',
      name: 'S24 Ultra 12/256 Гб Серый',
      price: 91500,
    },
    {
      category: 'Смартфоны',
      brand: 'Samsung',
      model: 'Samsung S24 Ultra',
      name: 'S24 Ultra 12/256 Гб Лаванда',
      price: 94000,
    },
    {
      category: 'Смартфоны',
      brand: 'Samsung',
      model: 'Samsung S24 Ultra',
      name: 'S24 Ultra 12/1 Тб Черный',
      price: 125000,
    },
    {
      category: 'Смартфоны',
      brand: 'Samsung',
      model: 'Samsung S24 Ultra',
      name: 'S24 Ultra 12/1 Тб Фиолетовый',
      price: 125000,
    },
    {
      category: 'Смартфоны',
      brand: 'Samsung',
      model: 'Samsung Z Flip',
      name: 'Z Flip 5 8/256 Бежевый',
      price: 58000,
    },
    {
      category: 'Смартфоны',
      brand: 'Samsung',
      model: 'Samsung Z Flip',
      name: 'Z Flip 5 8/512 Черный',
      price: 62000,
    },
    {
      category: 'Смартфоны',
      brand: 'Samsung',
      model: 'Samsung Z Flip',
      name: 'Z Flip 6 12/512 Желтый',
      price: 80000,
    },
    {
      category: 'Смартфоны',
      brand: 'Samsung',
      model: 'Samsung Z Flip',
      name: 'Z Flip 6 12/512 Мятный',
      price: 80000,
    },
    {
      category: 'Смартфоны',
      brand: 'Samsung',
      model: 'Samsung Z Fold',
      name: 'Z Fold 5 12/1 Тб Голубой',
      price: 118000,
    },
    {
      category: 'Смартфоны',
      brand: 'Samsung',
      model: 'Samsung Z Fold',
      name: 'Z Fold 6 12/256 Нави',
      price: 131000,
    },
    {
      category: 'Смартфоны',
      brand: 'Samsung',
      model: 'Samsung Z Fold',
      name: 'Z Fold 6 12/512 Белый',
      price: 140000,
    },
    {
      category: 'Смартфоны',
      brand: 'Samsung',
      model: 'Samsung Z Fold',
      name: 'Z Fold 6 12/1 Tb Черный',
      price: 143000,
    },
  
    // Xiaomi Смартфоны
    {
      category: 'Смартфоны',
      brand: 'Xiaomi',
      model: 'Xiaomi Mi 12',
      name: '12 8/128 Синий',
      price: 33000,
    },
    {
      category: 'Смартфоны',
      brand: 'Xiaomi',
      model: 'Xiaomi Mi 12',
      name: '12 12/256 Фиолетовый',
      price: 37500,
    },
    {
      category: 'Смартфоны',
      brand: 'Xiaomi',
      model: 'Xiaomi Mi 12 Lite',
      name: '12 Lite 8/256 Черный',
      price: 24000,
    },
    {
      category: 'Смартфоны',
      brand: 'Xiaomi',
      model: 'Xiaomi Mi 12 Pro',
      name: '12 Pro 12/256 Синий',
      price: 40500,
    },
    {
      category: 'Смартфоны',
      brand: 'Xiaomi',
      model: 'Xiaomi Mi 12 Pro',
      name: '12 Pro 12/256 Серый',
      price: 41000,
    },
    {
      category: 'Смартфоны',
      brand: 'Xiaomi',
      model: 'Xiaomi Mi 12 Pro',
      name: '12 Pro 12/256 Фиолетовый',
      price: 41000,
    },
    {
      category: 'Смартфоны',
      brand: 'Xiaomi',
      model: 'Xiaomi Mi 13T',
      name: '13T 12/256 Синий',
      price: 38000,
    },
    {
      category: 'Смартфоны',
      brand: 'Xiaomi',
      model: 'Xiaomi Mi 13T',
      name: '13T 12/256 Зеленый',
      price: 38000,
    },
    {
      category: 'Смартфоны',
      brand: 'Xiaomi',
      model: 'Xiaomi Mi 13T',
      name: '13T Pro 12/512 Зеленый',
      price: 49000,
    },
    {
      category: 'Смартфоны',
      brand: 'Xiaomi',
      model: 'Xiaomi Mi 14',
      name: '14 12/512 Белый',
      price: 72000,
    },
    {
      category: 'Смартфоны',
      brand: 'Xiaomi',
      model: 'Xiaomi Mi 14',
      name: '14 12/512 Черный',
      price: 74000,
    },
    {
      category: 'Смартфоны',
      brand: 'Xiaomi',
      model: 'Xiaomi Mi 14',
      name: '14 12/512 Зеленый',
      price: 73000,
    },
    {
      category: 'Смартфоны',
      brand: 'Xiaomi',
      model: 'Xiaomi Mi 14T',
      name: '14Т 12/256 Серый',
      price: 43000,
    },
    {
      category: 'Смартфоны',
      brand: 'Xiaomi',
      model: 'Xiaomi Mi 14T',
      name: '14Т 12/256 Черный',
      price: 43000,
    },
    {
      category: 'Смартфоны',
      brand: 'Xiaomi',
      model: 'Xiaomi Mi 14T',
      name: '14Т 12/256 Синий',
      price: 43000,
    },
    {
      category: 'Смартфоны',
      brand: 'Xiaomi',
      model: 'Xiaomi Mi 14T Pro',
      name: '14Т Pro 12/1Тб Синий',
      price: 68000,
    },
    {
      category: 'Смартфоны',
      brand: 'Xiaomi',
      model: 'Xiaomi Mi 14T Pro',
      name: '14Т Pro 12/1Тб Серый',
      price: 68000,
    },
    {
      category: 'Смартфоны',
      brand: 'Xiaomi',
      model: 'Xiaomi Mi 14T Pro',
      name: '14Т Pro 12/1Тб Черный',
      price: 68000,
    },
    {
      category: 'Смартфоны',
      brand: 'Xiaomi',
      model: 'Xiaomi Mi 14 Ultra',
      name: '14 Ultra 16/512 Черный',
      price: 98000,
    },
    {
      category: 'Смартфоны',
      brand: 'Xiaomi',
      model: 'Xiaomi Mi 14 Ultra',
      name: '14 Ultra 16/512 Белый',
      price: 96500,
    },
    {
      category: 'Смартфоны',
      brand: 'Xiaomi',
      model: 'Xiaomi Mi Mix Flip',
      name: 'Mi Mix Flip 12/512 Черный',
      price: 104000,
    },
    {
      category: 'Смартфоны',
      brand: 'Xiaomi',
      model: 'Xiaomi Mi Mix Flip',
      name: 'Mi Mix Flip 12/512 Фиолетовый',
      price: 104000,
    },
  
    // Redmi Смартфоны
    {
      category: 'Смартфоны',
      brand: 'Redmi',
      model: 'Redmi A3',
      name: 'Redmi A3 4/128 Гб Синий',
      price: 7000,
    },
    {
      category: 'Смартфоны',
      brand: 'Redmi',
      model: 'Redmi A3',
      name: 'Redmi A3 4/128 Гб Зеленый',
      price: 7000,
    },
    {
      category: 'Смартфоны',
      brand: 'Redmi',
      model: 'Redmi A3',
      name: 'Redmi A3 4/128 Гб Черный',
      price: 6700,
    },
    {
      category: 'Смартфоны',
      brand: 'Redmi',
      model: 'Redmi A3x',
      name: 'Redmi A3x 3/64 Гб Белый',
      price: 5700,
    },
    {
      category: 'Смартфоны',
      brand: 'Redmi',
      model: 'Redmi A3x',
      name: 'Redmi A3x 3/64 Гб Зеленый',
      price: 5700,
    },
    {
      category: 'Смартфоны',
      brand: 'Redmi',
      model: 'Redmi A3x',
      name: 'Redmi A3x 3/64 Гб Черный',
      price: 5700,
    },
    {
      category: 'Смартфоны',
      brand: 'Redmi',
      model: 'Redmi 10',
      name: 'Redmi 10А 3/64 Гб Синий',
      price: 8000,
    },
    {
      category: 'Смартфоны',
      brand: 'Redmi',
      model: 'Redmi 10',
      name: 'Redmi 10А 3/64 Гб Серебро',
      price: 8000,
    },
    {
      category: 'Смартфоны',
      brand: 'Redmi',
      model: 'Redmi 13',
      name: 'Redmi 13 8/128 Гб Синий',
      price: 13800,
    },
    {
      category: 'Смартфоны',
      brand: 'Redmi',
      model: 'Redmi 13',
      name: 'Redmi 13 8/128 Гб Золотой',
      price: 13800,
    },
    {
      category: 'Смартфоны',
      brand: 'Redmi',
      model: 'Redmi 13',
      name: 'Redmi 13 8/256 Гб Золотой',
      price: 14500,
    },
    {
      category: 'Смартфоны',
      brand: 'Redmi',
      model: 'Redmi 13',
      name: 'Redmi 13 8/256 Гб Синий',
      price: 14500,
    },
    {
      category: 'Смартфоны',
      brand: 'Redmi',
      model: 'Redmi 14C',
      name: 'Redmi 14С 4/128 Гб Зеленый',
      price: 9800,
    },
    {
      category: 'Смартфоны',
      brand: 'Redmi',
      model: 'Redmi 14C',
      name: 'Redmi 14С 4/128 Гб Фиолетовый',
      price: 9800,
    },
    {
      category: 'Смартфоны',
      brand: 'Redmi',
      model: 'Redmi 14C',
      name: 'Redmi 14С 4/128 Гб Синий',
      price: 9800,
    },
    {
      category: 'Смартфоны',
      brand: 'Redmi',
      model: 'Redmi 14C',
      name: 'Redmi 14С 4/128 Гб Черный',
      price: 9800,
    },
    {
      category: 'Смартфоны',
      brand: 'Redmi',
      model: 'Redmi 14C',
      name: 'Redmi 14С 8/256 Гб Фиолетовый',
      price: 12500,
    },
    {
      category: 'Смартфоны',
      brand: 'Redmi',
      model: 'Redmi Note 11 Pro',
      name: 'Note 11 Pro 8/128 ГБ Синий',
      price: 19000,
    },
    {
      category: 'Смартфоны',
      brand: 'Redmi',
      model: 'Redmi Note 12',
      name: 'Note 12 8/128 Гб Зеленый',
      price: 14000,
    },
    {
      category: 'Смартфоны',
      brand: 'Redmi',
      model: 'Redmi Note 12 Pro',
      name: 'Note 12 Pro 6/128 Гб Cиний',
      price: 19800,
    },
    {
      category: 'Смартфоны',
      brand: 'Redmi',
      model: 'Redmi Note 12 Pro',
      name: 'Note 12 Pro 5G 6/128 Гб Черный',
      price: 20000,
    },
    {
      category: 'Смартфоны',
      brand: 'Redmi',
      model: 'Redmi Note 12 Pro',
      name: 'Note 12 Pro 5G 6/128 Гб Синий',
      price: 20000,
    },
    {
      category: 'Смартфоны',
      brand: 'Redmi',
      model: 'Redmi Note 12 Pro',
      name: 'Note 12 Pro 5G 8/256 Гб Белый',
      price: 22000,
    },
    {
      category: 'Смартфоны',
      brand: 'Redmi',
      model: 'Redmi Note 12 Pro Plus',
      name: 'Note 12 Pro Plus 8/256 Синий',
      price: 27000,
    },
    {
      category: 'Смартфоны',
      brand: 'Redmi',
      model: 'Redmi Note 12S',
      name: 'Note 12S 8/256 Зеленый',
      price: 16500,
    },
    {
      category: 'Смартфоны',
      brand: 'Redmi',
      model: 'Redmi Note 12S',
      name: 'Note 12S 8/256 Синий',
      price: 16500,
    },
    {
      category: 'Смартфоны',
      brand: 'Redmi',
      model: 'Redmi Note 13',
      name: 'Note 13 8/128 Гб Черный',
      price: 14100,
    },
    {
      category: 'Смартфоны',
      brand: 'Redmi',
      model: 'Redmi Note 13 Pro',
      name: 'Note 13 Pro 8/256 Гб Зеленый',
      price: 23000,
    },
    {
      category: 'Смартфоны',
      brand: 'Redmi',
      model: 'Redmi Note 13 Pro',
      name: 'Note 13 Pro 8/256 Гб Черный',
      price: 23000,
    },
    {
      category: 'Смартфоны',
      brand: 'Redmi',
      model: 'Redmi Note 13 Pro',
      name: 'Note 13 Pro 5G 8/256 Гб Зеленый',
      price: 27000,
    },
    {
      category: 'Смартфоны',
      brand: 'Redmi',
      model: 'Redmi Note 13 Pro',
      name: 'Note 13 Pro 5G 8/256 Гб Фиолетовый',
      price: 27000,
    },
    {
      category: 'Смартфоны',
      brand: 'Redmi',
      model: 'Redmi Note 13 Pro',
      name: 'Note 13 Pro 5G 12/512 Гб Фиолетовый',
      price: 32000,
    },
    {
      category: 'Смартфоны',
      brand: 'Redmi',
      model: 'Redmi Note 13 Pro',
      name: 'Note 13 Pro 5G 12/512 Гб Синий',
      price: 32000,
    },
    {
      category: 'Смартфоны',
      brand: 'Redmi',
      model: 'Redmi Note 13 Pro Plus',
      name: 'Note 13 Pro Plus 5G 12/512 Гб Фиолетовый',
      price: 36000,
    },
    {
      category: 'Смартфоны',
      brand: 'Redmi',
      model: 'Redmi Note 13 Pro Plus',
      name: 'Note 13 Pro Plus 5G 12/512 Гб Черный',
      price: 36000,
    },
  
    // Poco Смартфоны
    {
      category: 'Смартфоны',
      brand: 'Poco',
      model: 'Poco C61',
      name: 'Poco С61 3/64 Черный',
      price: 5800,
    },
    {
      category: 'Смартфоны',
      brand: 'Poco',
      model: 'Poco C61',
      name: 'Poco С61 4/128 Белый',
      price: 6900,
    },
    {
      category: 'Смартфоны',
      brand: 'Poco',
      model: 'Poco C65',
      name: 'Poco С65 6/128 Синий',
      price: 9200,
    },
    {
      category: 'Смартфоны',
      brand: 'Poco',
      model: 'Poco C65',
      name: 'Poco С65 6/128 Фиолетовый',
      price: 9200,
    },
    {
      category: 'Смартфоны',
      brand: 'Poco',
      model: 'Poco C65',
      name: 'Poco С65 8/256 Черный',
      price: 10400,
    },
    {
      category: 'Смартфоны',
      brand: 'Poco',
      model: 'Poco C65',
      name: 'Poco С65 8/256 Синий',
      price: 10400,
    },
    {
      category: 'Смартфоны',
      brand: 'Poco',
      model: 'Poco C75',
      name: 'Poco С75 6/128 Зеленый',
      price: 12500,
    },
    {
      category: 'Смартфоны',
      brand: 'Poco',
      model: 'Poco C75',
      name: 'Poco С75 8/256 Зеленый',
      price: 14000,
    },
    {
      category: 'Смартфоны',
      brand: 'Poco',
      model: 'Poco C75',
      name: 'Poco С75 8/256 Золотой',
      price: 14000,
    },
    {
      category: 'Смартфоны',
      brand: 'Poco',
      model: 'Poco F4',
      name: 'Poco F4 6/128 ГБ Зеленый',
      price: 23500,
    },
    {
      category: 'Смартфоны',
      brand: 'Poco',
      model: 'Poco F5',
      name: 'Poco F5 8/256 Черный',
      price: 31500,
    },
    {
      category: 'Смартфоны',
      brand: 'Poco',
      model: 'Poco F5',
      name: 'Poco F5 8/256 Синий',
      price: 31500,
    },
    {
      category: 'Смартфоны',
      brand: 'Poco',
      model: 'Poco F5',
      name: 'Poco F5 12/256 Черный',
      price: 33000,
    },
    {
      category: 'Смартфоны',
      brand: 'Poco',
      model: 'Poco F5',
      name: 'Poco F5 12/256 Синий',
      price: 33000,
    },
    {
      category: 'Смартфоны',
      brand: 'Poco',
      model: 'Poco F5 Pro',
      name: 'Poco F5 Pro 12/256 Белый',
      price: 41500,
    },
    {
      category: 'Смартфоны',
      brand: 'Poco',
      model: 'Poco F5 Pro',
      name: 'Poco F5 Pro 12/512 Черный',
      price: 41500,
    },
    {
      category: 'Смартфоны',
      brand: 'Poco',
      model: 'Poco F6',
      name: 'Poco F6 8/256 Черный',
      price: 31300,
    },
    {
      category: 'Смартфоны',
      brand: 'Poco',
      model: 'Poco F6',
      name: 'Poco F6 8/256 Зеленый',
      price: 31300,
    },
    {
      category: 'Смартфоны',
      brand: 'Poco',
      model: 'Poco F6',
      name: 'Poco F6 12/512 Черный',
      price: 37000,
    },
    {
      category: 'Смартфоны',
      brand: 'Poco',
      model: 'Poco F6',
      name: 'Poco F6 12/512 Зеленый',
      price: 37000,
    },
    {
      category: 'Смартфоны',
      brand: 'Poco',
      model: 'Poco F6',
      name: 'Poco F6 12/512 Серый',
      price: 37000,
    },
    {
      category: 'Смартфоны',
      brand: 'Poco',
      model: 'Poco F6 Pro',
      name: 'Poco F6 Pro 12/256 Черный',
      price: 44000,
    },
    {
      category: 'Смартфоны',
      brand: 'Poco',
      model: 'Poco F6 Pro',
      name: 'Poco F6 Pro 16/1Тб Черный',
      price: 56000,
    },
    {
      category: 'Смартфоны',
      brand: 'Poco',
      model: 'Poco F6 Pro',
      name: 'Poco F6 Pro 16/1Тб Белый',
      price: 56000,
    },
    {
      category: 'Смартфоны',
      brand: 'Poco',
      model: 'Poco M6',
      name: 'Poco M6 6/128 Серебро',
      price: 12000,
    },
    {
      category: 'Смартфоны',
      brand: 'Poco',
      model: 'Poco M6',
      name: 'Poco M6 8/256 Фиолетовый',
      price: 14000,
    },
    {
      category: 'Смартфоны',
      brand: 'Poco',
      model: 'Poco M6 Pro',
      name: 'Poco M6 Pro 8/256 Синий',
      price: 18000,
    },
    {
      category: 'Смартфоны',
      brand: 'Poco',
      model: 'Poco M6 Pro',
      name: 'Poco M6 Pro 12/512 Фиолетовый',
      price: 21000,
    },
    {
      category: 'Смартфоны',
      brand: 'Poco',
      model: 'Poco M6 Pro',
      name: 'Poco M6 Pro 12/512 Черный',
      price: 21000,
    },
    {
      category: 'Смартфоны',
      brand: 'Poco',
      model: 'Poco X5 Pro',
      name: 'Poco X5 Pro 6/128 Желтый',
      price: 21000,
    },
    {
      category: 'Смартфоны',
      brand: 'Poco',
      model: 'Poco X6',
      name: 'Poco X6 8/256 Черный',
      price: 22500,
    },
    {
      category: 'Смартфоны',
      brand: 'Poco',
      model: 'Poco X6',
      name: 'Poco X6 12/256 Белый',
      price: 25000,
    },
    {
      category: 'Смартфоны',
      brand: 'Poco',
      model: 'Poco X6',
      name: 'Poco X6 12/512 Синий',
      price: 26500,
    },
    {
      category: 'Смартфоны',
      brand: 'Poco',
      model: 'Poco X6 Pro',
      name: 'Poco X6 Pro 8/256 Черный',
      price: 28000,
    },
    {
      category: 'Смартфоны',
      brand: 'Poco',
      model: 'Poco X6 Pro',
      name: 'Poco X6 Pro 8/256 Серый',
      price: 28000,
    },
    {
      category: 'Смартфоны',
      brand: 'Poco',
      model: 'Poco X6 Pro',
      name: 'Poco X6 Pro 12/512 Желтый',
      price: 32000,
    },
  
    // Realme Смартфоны
    {
      category: 'Смартфоны',
      brand: 'Realme',
      model: 'Realme 10',
      name: 'Realme 10 8/128 Черный',
      price: 18000,
    },
    {
      category: 'Смартфоны',
      brand: 'Realme',
      model: 'Realme 10',
      name: 'Realme 10 8/128 Белый',
      price: 18000,
    },
    {
      category: 'Смартфоны',
      brand: 'Realme',
      model: 'Realme 10',
      name: 'Realme 10 8/256 Черный',
      price: 18800,
    },
    {
      category: 'Смартфоны',
      brand: 'Realme',
      model: 'Realme 10',
      name: 'Realme 10 8/256 Белый',
      price: 18800,
    },
    {
      category: 'Смартфоны',
      brand: 'Realme',
      model: 'Realme 11 Pro',
      name: 'Realme 11 Pro 8/256 Черный',
      price: 27000,
    },
    {
      category: 'Смартфоны',
      brand: 'Realme',
      model: 'Realme 12 Pro',
      name: 'Realme 12 Pro Plus 8/256 Бежевый',
      price: 37000,
    },
    {
      category: 'Смартфоны',
      brand: 'Realme',
      model: 'Realme 13 Pro',
      name: 'Realme 13 Pro 12/512 Зеленый',
      price: 35000,
    },
    {
      category: 'Смартфоны',
      brand: 'Realme',
      model: 'Realme 13 Pro',
      name: 'Realme 13 Pro 12/512 Фиолетовый',
      price: 35000,
    },
    {
      category: 'Смартфоны',
      brand: 'Realme',
      model: 'Realme C33',
      name: 'Realme С33 4/64 Голубой',
      price: 8800,
    },
    {
      category: 'Смартфоны',
      brand: 'Realme',
      model: 'Realme C33',
      name: 'Realme С33 4/128 Голубой',
      price: 9200,
    },
    {
      category: 'Смартфоны',
      brand: 'Realme',
      model: 'Realme C61',
      name: 'Realme С61 6/128 Зеленый',
      price: 9000,
    },
    {
      category: 'Смартфоны',
      brand: 'Realme',
      model: 'Realme C61',
      name: 'Realme С61 8/256 Зеленый',
      price: 11000,
    },
    {
      category: 'Смартфоны',
      brand: 'Realme',
      model: 'Realme Note 50',
      name: 'Realme Note 50 3/64 Синий',
      price: 6400,
    },
    {
      category: 'Смартфоны',
      brand: 'Realme',
      model: 'Realme Note 50',
      name: 'Realme Note 50 4/256 Черный',
      price: 8300,
    },
    {
      category: 'Смартфоны',
      brand: 'Realme',
      model: 'Realme GT6/GT6T',
      name: 'Realme GT6Т 8/256 Серебро',
      price: 41000,
    },
    {
      category: 'Смартфоны',
      brand: 'Realme',
      model: 'Realme GT6/GT6T',
      name: 'Realme GT6Т 8/256 Зеленый',
      price: 41000,
    },
    {
      category: 'Смартфоны',
      brand: 'Realme',
      model: 'Realme GT6/GT6T',
      name: 'Realme GT6Т 12/256 Серебро',
      price: 47000,
    },
  
    // OnePlus Смартфоны
    {
      category: 'Смартфоны',
      brand: 'OnePlus',
      model: 'OnePlus Nord 4',
      name: 'OnePlus Nord 4 16/512 Green',
      price: 49000,
    },
    {
      category: 'Смартфоны',
      brand: 'OnePlus',
      model: 'OnePlus 12',
      name: 'OnePlus 12 16/512 Flowy',
      price: 73000,
    },
    {
      category: 'Смартфоны',
      brand: 'OnePlus',
      model: 'OnePlus 12',
      name: 'OnePlus 12 16/512 Black',
      price: 73000,
    },
  
    // OPPO Смартфоны
    {
      category: 'Смартфоны',
      brand: 'OPPO',
      model: 'OPPO A16K',
      name: 'A16K 3/32 Синий',
      price: 8000,
    },
    {
      category: 'Смартфоны',
      brand: 'OPPO',
      model: 'OPPO Reno 7',
      name: 'Reno 7 8/128 Черный',
      price: 18000,
    },
    {
      category: 'Смартфоны',
      brand: 'OPPO',
      model: 'OPPO Reno 10',
      name: 'Reno 10 8/256 Синий',
      price: 31000,
    },
  
    // Google Смартфоны
    {
      category: 'Смартфоны',
      brand: 'Google',
      model: 'Pixel 9 Pro',
      name: 'Pixel 9 Pro XL 256gb Черный',
      price: 105000,
    },
    {
      category: 'Смартфоны',
      brand: 'Google',
      model: 'Pixel 9 Pro',
      name: 'Pixel 9 Pro XL 512gb Черный',
      price: 115000,
    },
    {
      category: 'Смартфоны',
      brand: 'Google',
      model: 'Pixel 9 Pro',
      name: 'Pixel 9 Pro 256gb Ореховый',
      price: 97000,
    },
    {
      category: 'Смартфоны',
      brand: 'Google',
      model: 'Pixel 9',
      name: 'Pixel 9 256 Черный',
      price: 74000,
    },
    {
      category: 'Смартфоны',
      brand: 'Google',
      model: 'Pixel 8 Pro',
      name: 'Pixel 8 Pro 128 Синий',
      price: 61000,
    },
    {
      category: 'Смартфоны',
      brand: 'Google',
      model: 'Pixel 8 Pro',
      name: 'Pixel 8 Pro 128 Обсидиан',
      price: 61000,
    },
    {
      category: 'Смартфоны',
      brand: 'Google',
      model: 'Pixel 7 Pro',
      name: 'Pixel 7 Pro 128 Белый',
      price: 42000,
    },
    {
      category: 'Смартфоны',
      brand: 'Google',
      model: 'Pixel 7 Pro',
      name: 'Pixel 7 Pro 512 Черный',
      price: 56000,
    },
    {
      category: 'Смартфоны',
      brand: 'Google',
      model: 'Pixel 7',
      name: 'Pixel 7 128 Черный',
      price: 35000,
    },
    {
      category: 'Смартфоны',
      brand: 'Google',
      model: 'Pixel 7',
      name: 'Pixel 7 128 Желтый',
      price: 35000,
    },
    {
      category: 'Смартфоны',
      brand: 'Google',
      model: 'Pixel 7',
      name: 'Pixel 7 256 Черный',
      price: 41000,
    },
    {
      category: 'Смартфоны',
      brand: 'Google',
      model: 'Pixel 7A',
      name: 'Pixel 7А 128 Черный',
      price: 33000,
    },
  
    // Honor Смартфоны
    {
      category: 'Смартфоны',
      brand: 'Honor',
      model: 'Honor 200 Lite',
      name: 'Honor 200 Lite 8/256 Синий',
      price: 25500,
    },
    {
      category: 'Смартфоны',
      brand: 'Honor',
      model: 'Honor 200',
      name: 'Honor 200 8/256 Белый',
      price: 32500,
    },
    {
      category: 'Смартфоны',
      brand: 'Honor',
      model: 'Honor 200',
      name: 'Honor 200 12/512 Черный',
      price: 38000,
    },
    {
      category: 'Смартфоны',
      brand: 'Honor',
      model: 'Honor 200',
      name: 'Honor 200 12/512 Белый',
      price: 38000,
    },
    {
      category: 'Смартфоны',
      brand: 'Honor',
      model: 'Honor 200 Pro',
      name: 'Honor 200 Pro 12/512 Зеленый',
      price: 55500,
    },
    {
      category: 'Смартфоны',
      brand: 'Honor',
      model: 'Honor 200 Pro',
      name: 'Honor 200 Pro 12/512 Черный',
      price: 55500,
    },
    {
      category: 'Смартфоны',
      brand: 'Honor',
      model: 'Honor 200 Pro',
      name: 'Honor 200 Pro 12/512 Белый',
      price: 55500,
    },
    {
      category: 'Смартфоны',
      brand: 'Honor',
      model: 'Honor 90',
      name: 'Honor 90 8/256 Зеленый',
      price: 25500,
    },
    {
      category: 'Смартфоны',
      brand: 'Honor',
      model: 'Honor 90',
      name: 'Honor 90 12/512 Зеленый',
      price: 30000,
    },
    {
      category: 'Смартфоны',
      brand: 'Honor',
      model: 'Honor 90',
      name: 'Honor 90 12/512 Черный',
      price: 30000,
    },
    {
      category: 'Смартфоны',
      brand: 'Honor',
      model: 'Honor Magic',
      name: 'Honor Magic 6 Pro 16/1 Tb Черный',
      price: 89000,
    },
  
    // Huawei Смартфоны
    {
      category: 'Смартфоны',
      brand: 'Huawei',
      model: 'Huawei P60 Pro',
      name: 'P60 Pro 8/256 Белый',
      price: 51000,
    },
    {
      category: 'Смартфоны',
      brand: 'Huawei',
      model: 'Huawei Pura 70',
      name: 'Pura 70 12/256 Розовый',
      price: 47500,
    },
    {
      category: 'Смартфоны',
      brand: 'Huawei',
      model: 'Huawei Pura 70',
      name: 'Pura 70 12/256 Черный',
      price: 47500,
    },
    {
      category: 'Смартфоны',
      brand: 'Huawei',
      model: 'Huawei Pura 70',
      name: 'Pura 70 12/256 Белый',
      price: 47500,
    },
    {
      category: 'Смартфоны',
      brand: 'Huawei',
      model: 'Huawei Pura 70 Pro',
      name: 'Pura 70 Pro 12/512 Черный',
      price: 63000,
    },
    {
      category: 'Смартфоны',
      brand: 'Huawei',
      model: 'Huawei Pura 70 Pro',
      name: 'Pura 70 Pro 12/512 Белый',
      price: 64000,
    },
    {
      category: 'Смартфоны',
      brand: 'Huawei',
      model: 'Huawei Pura 70 Ultra',
      name: 'Pura 70 Ultra 16/512 Зеленый',
      price: 87000,
    },
    {
      category: 'Смартфоны',
      brand: 'Huawei',
      model: 'Huawei Pura 70 Ultra',
      name: 'Pura 70 Ultra 16/1 Tb Черный',
      price: 97000,
    },
  
    // Infinix Смартфоны
    {
      category: 'Смартфоны',
      brand: 'Infinix',
      model: 'Infinix Smart 9',
      name: 'Infinix Smart 9 3/128 Черный',
      price: 8500,
    },
    {
      category: 'Смартфоны',
      brand: 'Infinix',
      model: 'Infinix Smart 9',
      name: 'Infinix Smart 9 3/128 Зеленый',
      price: 8500,
    },
    {
      category: 'Смартфоны',
      brand: 'Infinix',
      model: 'Infinix Smart 9',
      name: 'Infinix Smart 9 3/128 Серый',
      price: 8500,
    },
    {
      category: 'Смартфоны',
      brand: 'Infinix',
      model: 'Infinix NOTE 40 Pro/HOT 40 Pro',
      name: 'Infinix NOTE 40 Pro 8/256 Зеленый',
      price: 21200,
    },
    {
      category: 'Смартфоны',
      brand: 'Infinix',
      model: 'Infinix NOTE 40 Pro/HOT 40 Pro',
      name: 'Infinix NOTE 40 Pro 12/256 Зеленый',
      price: 24500,
    },
    {
      category: 'Смартфоны',
      brand: 'Infinix',
      model: 'Infinix HOT 50',
      name: 'Infinix HOT 50i 6/128 Серый',
      price: 10300,
    },
    {
      category: 'Смартфоны',
      brand: 'Infinix',
      model: 'Infinix HOT 50',
      name: 'Infinix HOT 50i 6/128 Черный',
      price: 10300,
    },
    {
      category: 'Смартфоны',
      brand: 'Infinix',
      model: 'Infinix HOT 50',
      name: 'Infinix HOT 50i 6/128 Зеленый',
      price: 10300,
    },
    {
      category: 'Смартфоны',
      brand: 'Infinix',
      model: 'Infinix HOT 50',
      name: 'Infinix HOT 50 6/256 Зеленый',
      price: 14000,
    },
    {
      category: 'Смартфоны',
      brand: 'Infinix',
      model: 'Infinix HOT 50',
      name: 'Infinix HOT 50 6/256 Серый',
      price: 14000,
    },
    {
      category: 'Смартфоны',
      brand: 'Infinix',
      model: 'Infinix HOT 50',
      name: 'Infinix HOT 50 6/256 Черный',
      price: 14000,
    },
  
    // Nothing Смартфоны
    {
      category: 'Смартфоны',
      brand: 'Nothing',
      model: 'Nothing CMF Phone 1',
      name: 'CMF Phone 1 8/256 Черный',
      price: 24500,
    },
    {
      category: 'Смартфоны',
      brand: 'Nothing',
      model: 'Nothing CMF Phone 1',
      name: 'CMF Phone 1 8/256 Зеленый',
      price: 24500,
    },
    {
      category: 'Смартфоны',
      brand: 'Nothing',
      model: 'Nothing Phone 2A',
      name: 'Nothing Phone 2A 12/256 Черный',
      price: 35000,
    },
    {
      category: 'Смартфоны',
      brand: 'Nothing',
      model: 'Nothing Phone 2A',
      name: 'Nothing Phone 2A 12/256 Белый',
      price: 35000,
    },
    {
      category: 'Смартфоны',
      brand: 'Nothing',
      model: 'Nothing Phone 2A Plus',
      name: 'Nothing Phone 2A Plus 12/256 Черный',
      price: 40000,
    },
    {
      category: 'Смартфоны',
      brand: 'Nothing',
      model: 'Nothing Phone 2A Plus',
      name: 'Nothing Phone 2A Plus 12/256 Серый',
      price: 40000,
    },
  
    // Tecno Смартфоны
    {
      category: 'Смартфоны',
      brand: 'Tecno',
      model: 'Tecno Pova 6 Pro',
      name: 'Pova 6 Pro 12/256 Серый',
      price: 22200,
    },
    {
      category: 'Смартфоны',
      brand: 'Tecno',
      model: 'Tecno Pova 6 Neo',
      name: 'Pova 6 Neo 8/256 Черный',
      price: 15300,
    },
    {
      category: 'Смартфоны',
      brand: 'Tecno',
      model: 'Tecno Pova 6 Neo',
      name: 'Pova 6 Neo 8/256 Серебро',
      price: 15300,
    },
    {
      category: 'Смартфоны',
      brand: 'Tecno',
      model: 'Tecno Camon 30',
      name: 'Camon 30 8/256 Белый',
      price: 18300,
    },
    {
      category: 'Смартфоны',
      brand: 'Tecno',
      model: 'Tecno Camon 30',
      name: 'Camon 30 8/256 Черный',
      price: 18800,
    },
  
    // Игровые приставки и геймпады
    {
      category: 'Игровые приставки и геймпады',
      brand: 'Sony',
      model: 'Sony PS Portal/PS/DualSense',
      name: 'PS 5 Pro',
      price: 93000,
    },
    {
      category: 'Игровые приставки и геймпады',
      brand: 'Sony',
      model: 'Sony PS Portal/PS/DualSense',
      name: 'PS 5 Slim',
      price: 56500,
    },
    {
      category: 'Игровые приставки и геймпады',
      brand: 'Sony',
      model: 'Sony PS Portal/PS/DualSense',
      name: 'PS Portal Remote',
      price: 29000,
    },
    {
      category: 'Игровые приставки и геймпады',
      brand: 'Sony',
      model: 'Sony PS Portal/PS/DualSense',
      name: 'DualSense Фиолетовый',
      price: 7400,
    },
    {
      category: 'Игровые приставки и геймпады',
      brand: 'Sony',
      model: 'Sony PS Portal/PS/DualSense',
      name: 'DualSense Синий',
      price: 7400,
    },
  
    // Наушники
    {
      category: 'Наушники',
      brand: 'Apple',
      model: 'AirPods',
      name: 'Airpods 4',
      price: 15500,
    },
    {
      category: 'Наушники',
      brand: 'Apple',
      model: 'AirPods',
      name: 'Airpods 4 ANC',
      price: 18500,
    },
    {
      category: 'Наушники',
      brand: 'Apple',
      model: 'AirPods',
      name: 'Airpods Pro 2 USB-C',
      price: 22000,
    },
    {
      category: 'Наушники',
      brand: 'Apple',
      model: 'AirPods',
      name: 'Airpods Max Midnight USB-C',
      price: 68000,
    },
    {
      category: 'Наушники',
      brand: 'Apple',
      model: 'AirPods',
      name: 'Airpods Max Blue USB-C',
      price: 68000,
    },
    {
      category: 'Наушники',
      brand: 'Apple',
      model: 'AirPods',
      name: 'Airpods Max Orange USB-C',
      price: 68000,
    },
    {
      category: 'Наушники',
      brand: 'Samsung',
      model: 'Galaxy Buds',
      name: 'Buds 2 Pro Черный',
      price: 10000,
    },
    {
      category: 'Наушники',
      brand: 'Samsung',
      model: 'Galaxy Buds',
      name: 'Buds 2 Pro Фиолетовый',
      price: 10000,
    },
    {
      category: 'Наушники',
      brand: 'Samsung',
      model: 'Galaxy Buds',
      name: 'Buds 3 Серебро',
      price: 10500,
    },
    {
      category: 'Наушники',
      brand: 'Samsung',
      model: 'Galaxy Buds',
      name: 'Buds FE Белые',
      price: 5600,
    },
    {
      category: 'Наушники',
      brand: 'Samsung',
      model: 'Galaxy Buds',
      name: 'Buds FE Черные',
      price: 5600,
    },
    {
      category: 'Наушники',
      brand: 'Pixel',
      model: 'Pixel Buds Pro',
      name: 'Buds Pro Бежевые',
      price: 14500,
    },
    {
      category: 'Наушники',
      brand: 'OnePlus',
      model: 'OnePlus Buds',
      name: 'Buds Pro 2 Белые',
      price: 11500,
    },
  
    // Планшеты
    {
      category: 'Планшеты',
      brand: 'Xiaomi',
      model: 'Mi Pad/Redmi Pad/Redmi Pad Pro',
      name: 'Mi Pad 6 8/256 Gb Wi-Fi Gold',
      price: 32500,
    },
    {
      category: 'Планшеты',
      brand: 'Xiaomi',
      model: 'Mi Pad/Redmi Pad/Redmi Pad Pro',
      name: 'Redmi Pad Pro 8/256 Gb Wi-Fi Gray',
      price: 30000,
    },
    {
      category: 'Планшеты',
      brand: 'Xiaomi',
      model: 'Mi Pad/Redmi Pad/Redmi Pad Pro',
      name: 'Redmi Pad Pro 8/256 Gb Wi-Fi Blue',
      price: 30000,
    },
    {
      category: 'Планшеты',
      brand: 'Xiaomi',
      model: 'Mi Pad/Redmi Pad/Redmi Pad Pro',
      name: 'Redmi Pad SE 4/128 Gb Wi-Fi Purple',
      price: 14400,
    },
    {
      category: 'Планшеты',
      brand: 'Xiaomi',
      model: 'Mi Pad/Redmi Pad/Redmi Pad Pro',
      name: 'Redmi Pad SE 6/128 Gb Wi-Fi Green',
      price: 16000,
    },
    {
      category: 'Планшеты',
      brand: 'Samsung',
      model: 'Samsung Tab S7 FE',
      name: 'Tab S7 FE 4/64 Wi-Fi Черный',
      price: 33000,
    },
    {
      category: 'Планшеты',
      brand: 'Samsung',
      model: 'Samsung Tab S7 FE',
      name: 'Tab S7 FE 4/64 Wi-Fi Зеленый',
      price: 33000,
    },
    {
      category: 'Планшеты',
      brand: 'Samsung',
      model: 'Samsung Tab А9/A9 Plus',
      name: 'Tab А9 4/64 LTE Серебро',
      price: 13000,
    },
    {
      category: 'Планшеты',
      brand: 'Samsung',
      model: 'Samsung Tab А9/A9 Plus',
      name: 'Tab А9 4/64 LTE Нави',
      price: 13000,
    },
    {
      category: 'Планшеты',
      brand: 'Samsung',
      model: 'Samsung Tab S9 FE/S9 Plus',
      name: 'Tab S9 FE 6/128 Wi-Fi Зеленый',
      price: 33000,
    },
    {
      category: 'Планшеты',
      brand: 'Samsung',
      model: 'Samsung Tab S9 FE/S9 Plus',
      name: 'Tab S9 FE 8/256 Wi-Fi Серый',
      price: 38000,
    },
    {
      category: 'Планшеты',
      brand: 'Samsung',
      model: 'Samsung Tab S9 FE/S9 Plus',
      name: 'Tab S9 FE Plus 8/128 Wi-Fi Серый',
      price: 42000,
    },
    {
      category: 'Планшеты',
      brand: 'Samsung',
      model: 'Samsung Tab S9 FE/S9 Plus',
      name: 'Tab S9 FE Plus 12/256 Wi-Fi Серый',
      price: 52000,
    },
    {
      category: 'Планшеты',
      brand: 'Samsung',
      model: 'Samsung Tab S9 FE/S9 Plus',
      name: 'Чехол клавиатура Samsung Tab S9 FE Black',
      price: 14000,
    },
    {
      category: 'Планшеты',
      brand: 'Apple',
      model: 'iPad 10',
      name: 'iPad 10 64 WiFi Blue',
      price: 39000,
    },
    {
      category: 'Планшеты',
      brand: 'Apple',
      model: 'iPad Air',
      name: 'iPad Air (2022) 64 LTE Blue',
      price: 71000,
    },
    {
      category: 'Планшеты',
      brand: 'Apple',
      model: 'iPad Air',
      name: 'iPad Air (2022) 256 WiFi Purple',
      price: 69000,
    },
    {
      category: 'Планшеты',
      brand: 'Apple',
      model: 'iPad Air 11',
      name: 'iPad Air 11 M2 (2024) 128 WiFi Purple',
      price: 66000,
    },
    {
      category: 'Планшеты',
      brand: 'Apple',
      model: 'iPad Air 11',
      name: 'iPad Air 11 M2 (2024) 128 WiFi Starlight',
      price: 66000,
    },
    {
      category: 'Планшеты',
      brand: 'Apple',
      model: 'iPad Mini 6',
      name: 'iPad mini 256 WiFi Pink',
      price: 59000,
    },
    {
      category: 'Планшеты',
      brand: 'Apple',
      model: 'iPad Mini 6',
      name: 'iPad mini 256 WiFi Gray',
      price: 59000,
    },
    {
      category: 'Планшеты',
      brand: 'Apple',
      model: 'iPad Mini 6',
      name: 'iPad mini 256 WiFi Starlight',
      price: 59000,
    },
    {
      category: 'Планшеты',
      brand: 'Apple',
      model: 'iPad Mini 6',
      name: 'iPad mini 256 WiFi Purple',
      price: 59000,
    },
    {
      category: 'Планшеты',
      brand: 'Apple',
      model: 'iPad Pro 12.9” M2',
      name: 'iPad Pro 12.9” M2 (2022) 128 LTE Gray',
      price: 106000,
    },
    {
      category: 'Планшеты',
      brand: 'Apple',
      model: 'iPad Pro 12.9” M2',
      name: 'iPad Pro 12.9” M2 (2022) 128 LTE Silver',
      price: 106000,
    },
    {
      category: 'Планшеты',
      brand: 'Apple',
      model: 'iPad Pro 12.9” M2',
      name: 'iPad Pro 12.9” M2 (2022) 256 LTE Gray',
      price: 120000,
    },
    {
      category: 'Планшеты',
      brand: 'Apple',
      model: 'iPad Pro 11” M4',
      name: 'iPad Pro 11” M4 (2024) 256 Wi-Fi Black',
      price: 123000,
    },
    {
      category: 'Планшеты',
      brand: 'Apple',
      model: 'iPad Pro 11” M4',
      name: 'iPad Pro 11” M4 (2024) 256 Wi-Fi Silver',
      price: 123000,
    },
    {
      category: 'Планшеты',
      brand: 'Apple',
      model: 'iPad Pro 11” M4',
      name: 'iPad Pro 11” M4 (2024) 256 LTE Black',
      price: 134000,
    },
    {
      category: 'Планшеты',
      brand: 'Apple',
      model: 'iPad Pro 13” M4',
      name: 'iPad Pro 13” M4 (2024) 256 LTE Silver',
      price: 149000,
    },
    {
      category: 'Планшеты',
      brand: 'Apple',
      model: 'iPad Pro 13” M4',
      name: 'iPad Pro 13” M4 (2024) 256 LTE Black',
      price: 149000,
    },
  
    // Ноутбуки
    {
      category: 'Ноутбуки',
      brand: 'Apple',
      model: 'MacBook Air 13 M1',
      name: 'MacBook Air 13” 2020 M1 8/256 Gray',
      price: 72000,
    },
    {
      category: 'Ноутбуки',
      brand: 'Apple',
      model: 'MacBook Air 13 M1',
      name: 'MacBook Air 13” 2020 M1 8/256 Gold',
      price: 72000,
    },
    {
      category: 'Ноутбуки',
      brand: 'Apple',
      model: 'MacBook Air 13 M1',
      name: 'MacBook Air 13” 2020 M1 8/256 Silver',
      price: 72000,
    },
    {
      category: 'Ноутбуки',
      brand: 'Apple',
      model: 'MacBook Air 13 M3',
      name: 'MacBook Air 13” 2024 M3 8/256 Gray',
      price: 106000,
    },
    {
      category: 'Ноутбуки',
      brand: 'Apple',
      model: 'MacBook Air 13 M3',
      name: 'MacBook Air 13” 2024 M3 8/512 Gray',
      price: 131000,
    },
    {
      category: 'Ноутбуки',
      brand: 'Apple',
      model: 'MacBook Air 13 M3',
      name: 'MacBook Air 13” 2024 M3 8/512 Midnight',
      price: 131000,
    },
    {
      category: 'Ноутбуки',
      brand: 'Apple',
      model: 'MacBook Air 15 M2',
      name: 'MacBook Air 15” 2023 M2 8/512 Midnight',
      price: 126000,
    },
    {
      category: 'Ноутбуки',
      brand: 'Apple',
      model: 'MacBook Air 15 M3',
      name: 'MacBook Air 15” 2024 M3 8/256 Midnight',
      price: 130000,
    },
    {
      category: 'Ноутбуки',
      brand: 'Apple',
      model: 'MacBook Air 15 M3',
      name: 'MacBook Air 15” 2024 M3 8/256 Silver',
      price: 130000,
    },
    {
      category: 'Ноутбуки',
      brand: 'Apple',
      model: 'MacBook Air 15 M3',
      name: 'MacBook Air 15” 2024 M3 8/256 Gray',
      price: 130000,
    },
    {
      category: 'Ноутбуки',
      brand: 'Apple',
      model: 'MacBook Air 15 M3',
      name: 'MacBook Air 15” 2024 M3 8/512 Midnight',
      price: 142000,
    },
    {
      category: 'Ноутбуки',
      brand: 'Apple',
      model: 'MacBook Air 15 M3',
      name: 'MacBook Air 15” 2024 M3 8/512 Silver',
      price: 142000,
    },
    {
      category: 'Ноутбуки',
      brand: 'Apple',
      model: 'MacBook Pro 14 M2 Pro',
      name: 'MacBook Pro 14” M2 Pro 16/1Tb Gray',
      price: 225000,
    },
    {
      category: 'Ноутбуки',
      brand: 'Apple',
      model: 'MacBook Pro 14 M2 Pro',
      name: 'MacBook Pro 14” M2 Pro 16/1Tb Silver',
      price: 225000,
    },
    {
      category: 'Ноутбуки',
      brand: 'Apple',
      model: 'MacBook Pro 14 M3/M3 Pro',
      name: 'MacBook Pro 14” M3 8/512 Gray',
      price: 140000,
    },
    {
      category: 'Ноутбуки',
      brand: 'Apple',
      model: 'MacBook Pro 14 M3/M3 Pro',
      name: 'MacBook Pro 14” M3 8/512 Silver',
      price: 140000,
    },
    {
      category: 'Ноутбуки',
      brand: 'Apple',
      model: 'MacBook Pro 14 M3/M3 Pro',
      name: 'MacBook Pro 14” M3 8/1Tb Silver',
      price: 159000,
    },
    {
      category: 'Ноутбуки',
      brand: 'Apple',
      model: 'MacBook Pro 14 M3/M3 Pro',
      name: 'MacBook Pro 14” M3 8/1Tb Gray',
      price: 159000,
    },
    {
      category: 'Ноутбуки',
      brand: 'Apple',
      model: 'MacBook Pro 14 M3/M3 Pro',
      name: 'MacBook Pro 14” M3 Pro 18/1Tb Silver',
      price: 232000,
    },
    {
      category: 'Ноутбуки',
      brand: 'Apple',
      model: 'MacBook Pro 14 M3/M3 Pro',
      name: 'MacBook Pro 14” M3 Pro 18/1Tb Black',
      price: 232000,
    },
    {
      category: 'Ноутбуки',
      brand: 'Apple',
      model: 'MacBook Pro 14 M4/M4 Pro',
      name: 'MacBook Pro 14” M4 Pro 24/512 Space Black',
      price: 225000,
    },
    {
      category: 'Ноутбуки',
      brand: 'Apple',
      model: 'MacBook Pro 16 M1 Pro',
      name: 'MacBook Pro 16” M1 Pro 16/1Tb Gray',
      price: 193000,
    },
    {
      category: 'Ноутбуки',
      brand: 'Apple',
      model: 'MacBook Pro 16 M3 Pro',
      name: 'MacBook Pro 16” M3 Pro 36/512 Silver',
      price: 260000,
    },
    {
      category: 'Ноутбуки',
      brand: 'Apple',
      model: 'MacBook Pro 16 M3 Pro',
      name: 'MacBook Pro 16” M3 Pro 36/512 Gray',
      price: 260000,
    },
    {
      category: 'Ноутбуки',
      brand: 'Apple',
      model: 'MacBook Pro 16 M3 Max',
      name: 'MacBook Pro 16” M3 Max 48/1 Tb Silver',
      price: 353000,
    },
  
    // Колонки
    {
      category: 'Колонки',
      brand: 'Яндекс',
      model: 'Яндекс Станция',
      name: 'Яндекс Станция Дуо Макс Зеленая Zigbee',
      price: 38000,
    },
    {
      category: 'Колонки',
      brand: 'Яндекс',
      model: 'Яндекс Станция',
      name: 'Яндекс Станция Дуо Макс Черная Zigbee',
      price: 38000,
    },
    {
      category: 'Колонки',
      brand: 'Яндекс',
      model: 'Яндекс Станция',
      name: 'Яндекс Станция Дуо Макс Красная Zigbee',
      price: 38000,
    },
    {
      category: 'Колонки',
      brand: 'Яндекс',
      model: 'Яндекс Станция',
      name: 'Яндекс Станция Макс Зеленая Zigbee',
      price: 29000,
    },
    {
      category: 'Колонки',
      brand: 'Яндекс',
      model: 'Яндекс Станция',
      name: 'Яндекс Станция Макс Бирюзовая Zigbee',
      price: 29000,
    },
    {
      category: 'Колонки',
      brand: 'Яндекс',
      model: 'Яндекс Станция',
      name: 'Яндекс Станция Макс Черная Zigbee',
      price: 29000,
    },
    {
      category: 'Колонки',
      brand: 'Яндекс',
      model: 'Яндекс Станция',
      name: 'Яндекс Станция Макс Бежевая Zigbee',
      price: 29000,
    },
    {
      category: 'Колонки',
      brand: 'Яндекс',
      model: 'Яндекс Станция',
      name: 'Яндекс Станция Миди Изумрудная',
      price: 13900,
    },
    {
      category: 'Колонки',
      brand: 'Яндекс',
      model: 'Яндекс Станция',
      name: 'Яндекс Станция Миди Малиновая',
      price: 13900,
    },
    {
      category: 'Колонки',
      brand: 'Яндекс',
      model: 'Яндекс Станция',
      name: 'Яндекс Станция Миди Серая',
      price: 13900,
    },
    {
      category: 'Колонки',
      brand: 'Яндекс',
      model: 'Яндекс Станция',
      name: 'Яндекс Станция Миди Черная',
      price: 13900,
    },
    {
      category: 'Колонки',
      brand: 'Яндекс',
      model: 'Яндекс Станция',
      name: 'Яндекс Станция Миди Оранжевая',
      price: 13900,
    },
    {
      category: 'Колонки',
      brand: 'Яндекс',
      model: 'Яндекс Станция',
      name: 'Яндекс Станция 2 Красная',
      price: 14500,
    },
    {
      category: 'Колонки',
      brand: 'Яндекс',
      model: 'Яндекс Станция',
      name: 'Яндекс Станция 2 Синяя',
      price: 14500,
    },
    {
      category: 'Колонки',
      brand: 'Яндекс',
      model: 'Яндекс Станция',
      name: 'Яндекс Станция 2 Медная',
      price: 14500,
    },
    {
      category: 'Колонки',
      brand: 'Яндекс',
      model: 'Яндекс Станция',
      name: 'Яндекс Станция 2 Черная',
      price: 14500,
    },
    {
      category: 'Колонки',
      brand: 'Яндекс',
      model: 'Яндекс Станция',
      name: 'Яндекс Станция Мини 2 Черная (без часов)',
      price: 6300,
    },
    {
      category: 'Колонки',
      brand: 'Яндекс',
      model: 'Яндекс Станция',
      name: 'Яндекс Станция Мини 2 Синяя (с часами)',
      price: 7100,
    },
    {
      category: 'Колонки',
      brand: 'Яндекс',
      model: 'Яндекс Станция',
      name: 'Яндекс Станция Мини 3 Лиловая (с часами)',
      price: 8500,
    },
    {
      category: 'Колонки',
      brand: 'Яндекс',
      model: 'Яндекс Станция',
      name: 'Яндекс Станция Мини 3 Черная (с часами)',
      price: 8500,
    },
    {
      category: 'Колонки',
      brand: 'Яндекс',
      model: 'Яндекс Станция',
      name: 'Яндекс Станция Лайт 2 Синяя',
      price: 5300,
    },
    {
      category: 'Колонки',
      brand: 'Яндекс',
      model: 'Яндекс Станция',
      name: 'Яндекс Станция Лайт 2 Зеленая',
      price: 5300,
    },
    {
      category: 'Колонки',
      brand: 'JBL',
      model: 'JBL Flip 6',
      name: 'JBL Flip 6 Бирюзовая',
      price: 8800,
    },
    {
      category: 'Колонки',
      brand: 'JBL',
      model: 'JBL Charger 5',
      name: 'JBL Charger 5 Синяя',
      price: 14000,
    },
    {
      category: 'Колонки',
      brand: 'JBL',
      model: 'JBL Charger 5',
      name: 'JBL Charger 5 Серая',
      price: 14000,
    },
    {
      category: 'Колонки',
      brand: 'JBL',
      model: 'JBL Charger 5',
      name: 'JBL Charger 5 Камуфляж',
      price: 14000,
    },
    {
      category: 'Колонки',
      brand: 'JBL',
      model: 'JBL Charger 5',
      name: 'JBL Charger 5 Красная',
      price: 14000,
    },
    {
      category: 'Колонки',
      brand: 'JBL',
      model: 'JBL Charger 5',
      name: 'JBL Charger 5 Бирюзовая',
      price: 14000,
    },
  
    // Красота
    {
      category: 'Красота',
      brand: 'Dyson',
      model: 'Dyson HS05 Long',
      name: 'Dyson HS05 Long Blue/Blush',
      price: 52000,
    },
    {
      category: 'Красота',
      brand: 'Dyson',
      model: 'Dyson HS05 Long',
      name: 'Dyson HS05 Long Strawberry Bronze/Blush Pink',
      price: 58500,
    },
    {
      category: 'Красота',
      brand: 'Dyson',
      model: 'Dyson HS08 Long',
      name: 'Dyson HS08 Long Patina/Topaz',
      price: 59000,
    },
    {
      category: 'Красота',
      brand: 'Dyson',
      model: 'Dyson HS08 Long',
      name: 'Dyson HS08 Long Strawberry/Pink',
      price: 64000,
    },
    {
      category: 'Красота',
      brand: 'Dyson',
      model: 'Dyson HS08 Long',
      name: 'Dyson HS08 Long Blue/Orange',
      price: 59000,
    },
    {
      category: 'Красота',
      brand: 'Dyson',
      model: 'Dyson HS07',
      name: 'Dyson HS07 Corrale Nickel/Cooper',
      price: 35000,
    },
    {
      category: 'Красота',
      brand: 'Dyson',
      model: 'Dyson HD16',
      name: 'Dyson HD16 Blue/Topaz Orange',
      price: 48000,
    },
    {
      category: 'Красота',
      brand: 'Dyson',
      model: 'Dyson HD16',
      name: 'Dyson HD16 Patina/Topaz',
      price: 48000,
    },
    {
      category: 'Красота',
      brand: 'Dyson',
      model: 'Dyson HT01',
      name: 'Dyson HT01 Airstrait Blue/Copper',
      price: 44000,
    },
    {
      category: 'Красота',
      brand: 'Dyson',
      model: 'Dyson HT01',
      name: 'Dyson HT01 Airstrait Nikel/Copper',
      price: 44000,
    },
    {
      category: 'Красота',
      brand: 'Dyson',
      model: 'Dyson HT01',
      name: 'Dyson HT01 Airstrait Ceramic/Pink',
      price: 44000,
    },
    {
      category: 'Красота',
      brand: 'Dyson',
      model: 'Dyson SuperSonic HD08',
      name: 'Dyson SuperSonic HD08 Blue/Cuper',
      price: 38000,
    },
    {
      category: 'Красота',
      brand: 'Dyson',
      model: 'Dyson SuperSonic HD08',
      name: 'Dyson SuperSonic HD08 Nickel/Cooper',
      price: 38000,
    },
  
    // Аксессуары Apple
    {
      category: 'Аксессуары Apple',
      brand: 'Apple',
      model: 'Apple Pencil',
      name: 'Apple Pencil USB-C',
      price: 9000,
    },
    {
      category: 'Аксессуары Apple',
      brand: 'Apple',
      model: 'Apple Pencil',
      name: 'Apple Pencil 2',
      price: 12500,
    },
    {
      category: 'Аксессуары Apple',
      brand: 'Apple',
      model: 'AirTag',
      name: 'AirTag',
      price: 4000,
    },
    {
      category: 'Аксессуары Apple',
      brand: 'Apple',
      model: 'AirTag',
      name: 'AirTag (4 pack)',
      price: 10200,
    },
    {
      category: 'Аксессуары Apple',
      brand: 'Apple',
      model: 'Home Pod',
      name: 'Home Pod mini Blue',
      price: 12600,
    },
    {
      category: 'Аксессуары Apple',
      brand: 'Apple',
      model: 'Home Pod',
      name: 'Home Pod 2 Silver',
      price: 38600,
    },
    {
      category: 'Аксессуары Apple',
      brand: 'Apple',
      model: 'Apple Mouse',
      name: 'Apple Mouse 3 Black',
      price: 9800,
    },
    {
      category: 'Аксессуары Apple',
      brand: 'Apple',
      model: 'Apple Mouse',
      name: 'Apple Mouse 3 White',
      price: 9000,
    },
    {
      category: 'Аксессуары Apple',
      brand: 'Apple',
      model: 'Keyboard iPad',
      name: 'Keyboard iPad Pro 11 M4 magic White',
      price: 31400,
    },
    {
      category: 'Аксессуары Apple',
      brand: 'Apple',
      model: 'Keyboard iPad',
      name: 'Keyboard iPad Pro 12.9 M2 magic White',
      price: 33400,
    },
  
    // Аксессуары Samsung
    {
      category: 'Аксессуары Samsung',
      brand: 'Samsung',
      model: 'Galaxy Smart Tag',
      name: 'Galaxy Smart Tag Black',
      price: 2000,
    },
    {
      category: 'Аксессуары Samsung',
      brand: 'Samsung',
      model: 'Galaxy Smart Tag',
      name: 'Galaxy Smart Tag White',
      price: 2000,
    },
  ];
  
  

  // Вставляем данные в таблицу
  for (const product of productsData) {
    await db.run(
      'INSERT INTO products (category, brand, model, name, price) VALUES (?, ?, ?, ?, ?)',
      [product.category, product.brand, product.model, product.name, product.price]
    );
  }

  console.log('Данные успешно добавлены в таблицу products.');
  await db.close();
}

initializeDatabase().catch((err) => {
  console.error('Ошибка при инициализации базы данных:', err);
});